---
id: heiseirubykaigi-1
base_name: slide
tags: ['Windows', 'Middleman']
presentation_date: 2019-12-14
presentation_start_time: 14:05
presentation_end_time: 14:20
version: 1.0.0
licenses: ['CC-BY-SA-4.0']
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: unasuke
  email: yusuke1994525@gmail.com
  rubygems_user: unasuke
  slideshare_user: 
  speaker_deck_user: 
